-- Daemoon — initial schema (Supabase).
-- Apply via Supabase studio SQL editor or supabase.run_sql.

-- Per-user provider token vault (envelope encryption — see encryption.ts).
create table if not exists public.daemoon_tokens (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  provider          text not null,
  -- Envelope ciphertext for the access token.
  ciphertext        text not null,
  iv1               text not null,
  tag1              text not null,
  wrapped_dek       text not null,
  iv2               text not null,
  tag2              text not null,
  key_version       int  not null,
  -- Refresh token, encrypted with the same envelope shape.
  refresh_token_enc jsonb,
  expires_at        timestamptz,
  provider_user_id  text,
  meta              jsonb,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (user_id, provider)
);

-- Per-user audit log of every MCP tool invocation.
create table if not exists public.daemoon_audit (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  provider      text not null,
  tool          text not null,
  ok            boolean not null,
  error         text,
  duration_ms   int,
  created_at    timestamptz not null default now()
);
create index if not exists daemoon_audit_user_created on public.daemoon_audit (user_id, created_at desc);

-- RLS: block all direct access from anon/authenticated; only service_role on the server.
alter table public.daemoon_tokens enable row level security;
alter table public.daemoon_audit  enable row level security;
revoke all on public.daemoon_tokens from anon, authenticated;
revoke all on public.daemoon_audit  from anon, authenticated;

-- A safe own-rows view: list a user's connections without exposing token columns.
create or replace view public.daemoon_my_connections as
  select user_id, provider, provider_user_id, meta, created_at, updated_at, expires_at
  from public.daemoon_tokens
  where user_id = auth.uid();

grant select on public.daemoon_my_connections to authenticated;
