-- Daemun — initial schema (Supabase).
-- 적용: supabase studio SQL editor 또는 supabase.run_sql.

-- per-user provider token vault (envelope encryption — encryption.ts 참고)
create table if not exists public.daemun_tokens (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  provider          text not null,
  -- envelope ciphertext for the access token
  ciphertext        text not null,
  iv1               text not null,
  tag1              text not null,
  wrapped_dek       text not null,
  iv2               text not null,
  tag2              text not null,
  key_version       int  not null,
  -- 동일 envelope shape 로 refresh token
  refresh_token_enc jsonb,
  expires_at        timestamptz,
  provider_user_id  text,
  meta              jsonb,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (user_id, provider)
);

-- per-user 호출 감사 로그 (MCP 통해 어떤 도구가 호출됐는지)
create table if not exists public.daemun_audit (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  provider      text not null,
  tool          text not null,
  args_summary  jsonb,                 -- 민감 정보 제외하고 요약 (token 절대 X)
  ok            boolean not null,
  error         text,
  duration_ms   int,
  created_at    timestamptz not null default now()
);
create index if not exists daemun_audit_user_created on public.daemun_audit (user_id, created_at desc);

-- RLS — anon/auth 모두 직접 접근 차단. server (service_role) 만.
alter table public.daemun_tokens enable row level security;
alter table public.daemun_audit  enable row level security;
revoke all on public.daemun_tokens from anon, authenticated;
revoke all on public.daemun_audit  from anon, authenticated;

-- 사용자가 자기 *목록* 만 보는 것은 안전 — 토큰 컬럼은 보이지 않게 별 view
create or replace view public.daemun_my_connections as
  select user_id, provider, provider_user_id, meta, created_at, updated_at, expires_at
  from public.daemun_tokens
  where user_id = auth.uid();

grant select on public.daemun_my_connections to authenticated;
